#!/usr/bin/env bash

# {'GalleryNumber': '774',
#  'accessionNumber': '1976.97',
#  'accessionYear': '1976',
#  'additionalImages': ['https://images.metmuseum.org/CRDImages/ma/original/DP252075.jpg',
#                       'https://images.metmuseum.org/CRDImages/ma/original/208216.jpg'],
#  'artistAlphaSort': 'Ohr, George E.',
#  'artistBeginDate': '1857',
#  'artistDisplayBio': 'American, Biloxi, Mississippi 1857–1918  Biloxi, '
#                      'Mississippi',
#  'artistDisplayName': 'George E. Ohr',
#  'artistEndDate': '1918',
#  'artistGender': '',
#  'artistNationality': 'American',
#  'artistPrefix': '',
#  'artistRole': 'Maker',
#  'artistSuffix': '',
#  'artistULAN_URL': 'http://vocab.getty.edu/page/ulan/500071841',
#  'artistWikidata_URL': 'https://www.wikidata.org/wiki/Q5538774',
#  'city': 'Biloxi',
#  'classification': 'Ceramics',
#  'constituents': [{'constituentID': 165599,
#                    'constituentULAN_URL': 'http://vocab.getty.edu/page/ulan/500071841',
#                    'constituentWikidata_URL': 'https://www.wikidata.org/wiki/Q5538774',
#                    'gender': '',
#                    'name': 'George E. Ohr',
#                    'role': 'Maker'},
#                   {'constituentID': 1911,
#                    'constituentULAN_URL': '',
#                    'constituentWikidata_URL': '',
#                    'gender': '',
#                    'name': 'Biloxi Art Pottery',
#                    'role': 'Manufacturer'}],
#  'country': 'United States',
#  'county': '',
#  'creditLine': 'Purchase, Virginia H. Groomes Gift, in memory of her mother, '
#                'Mary W. Groomes, 1976',
#  'culture': 'American',
#  'department': 'Modern and Contemporary Art',
#  'dimensions': 'H. 4 1/4 in. (10.8 cm); Diam. 5 3/4 in. (14.6 cm)',
#  'dynasty': '',
#  'excavation': '',
#  'geographyType': 'Made in',
#  'isHighlight': False,
#  'isPublicDomain': True,
#  'isTimelineWork': False,
#  'linkResource': '',
#  'locale': '',
#  'locus': '',
#  'measurements': [{'elementDescription': None,
#                    'elementMeasurements': {'Diameter': 14.605,
#                                            'Height': 10.795},
#                    'elementName': 'Other'}],
#  'medium': 'Earthenware',
#  'metadataDate': '2020-09-16T18:35:19.457Z',
#  'objectBeginDate': 1894,
#  'objectDate': '1894–1906',
#  'objectEndDate': 1906,
#  'objectID': 9367,
#  'objectName': 'Vase',
#  'objectURL': 'https://www.metmuseum.org/art/collection/search/9367',
#  'objectWikidata_URL': '',
#  'period': '',
#  'portfolio': '',
#  'primaryImage': 'https://images.metmuseum.org/CRDImages/ma/original/DP252074.jpg',
#  'primaryImageSmall': 'https://images.metmuseum.org/CRDImages/ma/web-large/DP252074.jpg',
#  'region': 'South United States',
#  'reign': '',
#  'repository': 'Metropolitan Museum of Art, New York, NY',
#  'rightsAndReproduction': '',
#  'river': '',
#  'state': 'Mississippi',
#  'subregion': '',
#  'tags': [{'AAT_URL': 'http://vocab.getty.edu/page/aat/300132254',
#            'Wikidata_URL': 'https://www.wikidata.org/wiki/Q191851',
#            'term': 'Vases'}],
#  'title': 'Vase'}

sqlite3 the_met.db <<EOF
CREATE TABLE objects (
    object_id TEXT UNIQUE,
    object_title TEXT,
    object_artist TEXT,
    object_date TEXT,
    object_classification TEXT,
    object_medium TEXT,
    object_country TEXT,
    object_culture TEXT,
    object_region TEXT,
    object_subregion TEXT,
    object_primary_image TEXT,
    object_addtl_images TEXT,
    image_selected_date TEXT
);
EOF
